spring:
  data:
    mongodb:
      uri: ${mongo-uri}/PetDB?authSource=admin
PetMSService:
  Invalid:
    Species:
      Breed: "Breed is not Compatible with Species"
PetMSApi:
 Pet:
  Added:
   Successful: "New Pet Added with petId : "
