
spring:
  data:
    mongodb:
      uri: ${mongo-uri}/UserDB?authSource=admin

UserMSService:
  Email:
    Already:
      Used: "This email is already in use. Please try a different one."
    NotFound: "We couldn't find an account with that email address."

  Phone:
    Already:
      Used: "This phone number is already in use. Please try a different one."
    NotFound: "We couldn't find an account with that phone number."

  Password:
    Not:
      Match: "The password you entered is incorrect. Please try again."

UserMSApi:
  User:
    Registration:
      Success: "You've successfully registered!"

  Shelter:
    Worker:
      Registration:
        Success: "Shelter worker registered successfully!"

  Password:
    Update:
      Success: "Your password has been updated!"
