spring:
  data:
    mongodb:
      uri: ${mongo-uri}/UserDB?authSource=admin

UserMSService:
  Email:
    Already:
      Used: "Email is already registered as a {role}. Please use a different email."
    NotFound: "No account found with the provided email for role {role}."

  Phone:
    Already:
      Used: "Phone number is already registered as a {role}. Please use a different phone number."
    NotFound: "No account found with the provided phone number for role {role}."

  Password:
    Not:
      Match: "Incorrect password. Please try again."

UserMSApi:
  User:
    Registration:
      Success: "User registered successfully"

  Shelter:
    Worker:
      Registration:
        Success: "Shelter worker registered successfully"

  Password:
    Update:
      Success: "Password updated successfully"


